SUPERADMIN_ROLE_ID = 1
SUPERADMIN_ROLE_NAME = "SuperAdmin"
SUPERADMIN_ROLE_TITLE_KEY = "role.super_admin.title"

ADMIN_ROLE_TITLE_KEY = "role.admin.title"
USER_ROLE_TITLE_KEY = "role.user.title"
GUEST_ROLE_TITLE_KEY = "role.guest.title"
TEACHER_ROLE_TITLE_KEY = "role.teacher.title"
STUDENT_ROLE_TITLE_KEY = "role.student.title"

DEFAULT_ROLES: tuple[tuple[int, str, str], ...] = (
    (SUPERADMIN_ROLE_ID, SUPERADMIN_ROLE_NAME, SUPERADMIN_ROLE_TITLE_KEY),
    (2, "Admin", ADMIN_ROLE_TITLE_KEY),
    (3, "User", USER_ROLE_TITLE_KEY),
    (4, "Guest", GUEST_ROLE_TITLE_KEY),
    (5, "Teacher", TEACHER_ROLE_TITLE_KEY),
    (6, "Student", STUDENT_ROLE_TITLE_KEY),
)

DEFAULT_SIGNUP_ROLE_ID = 6
DEFAULT_SIGNUP_ROLE_NAME = "Student"
DEFAULT_SIGNUP_ROLE_TITLE_KEY = STUDENT_ROLE_TITLE_KEY
