"""initial schema

Revision ID: e8484413100f
Revises: 
Create Date: 2026-02-25 15:18:46.624208+00:00

"""
from alembic import op
import sqlalchemy as sa
from typing import Sequence, Union




# revision identifiers, used by Alembic.
revision: str = 'e8484413100f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_revoked_token_jtis",
        sa.Column("jti", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_auth_revoked_token_jtis_expires_at"),
        "auth_revoked_token_jtis",
        ["expires_at"],
        unique=False,
    )

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("title_key", sa.String(length=128), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_table(
        "translate_large",
        sa.Column("key1", sa.String(length=128), nullable=False),
        sa.Column("key2", sa.String(length=128), nullable=False),
        sa.Column("description", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key1", "key2"),
    )
    op.create_index("ix_translate_large_key1", "translate_large", ["key1"], unique=False)
    op.create_index(
        "ix_translate_large_key1_key2",
        "translate_large",
        ["key1", "key2"],
        unique=False,
    )

    op.create_table(
        "translate_small",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("title", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("translate_small")
    op.drop_index("ix_translate_large_key1_key2", table_name="translate_large")
    op.drop_index("ix_translate_large_key1", table_name="translate_large")
    op.drop_table("translate_large")
    op.drop_table("roles")
    op.drop_index(op.f("ix_auth_revoked_token_jtis_expires_at"), table_name="auth_revoked_token_jtis")
    op.drop_table("auth_revoked_token_jtis")
    # ### end Alembic commands ###
